# These are supported funding model platforms
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

patreon: Alex_Ai14
# github: alexandruradu2002-pixel
# ko_fi: your_username
# custom: ['https://your-link.com']
